CREATE OR REPLACE VIEW VIEW_CLIENTES AS
SELECT * FROM CLIENTES;

CREATE OR REPLACE VIEW VIEW_MASCOTAS AS
SELECT * FROM MASCOTAS;

CREATE OR REPLACE VIEW VIEW_VETERINARIOS AS
SELECT * FROM VETERINARIOS;

CREATE OR REPLACE VIEW VIEW_PROVEEDOR_PRODUCTOS AS
SELECT * FROM PROVEEDOR_PRODUCTOS;

CREATE OR REPLACE VIEW VIEW_PROVEEDOR_VACUNAS AS
SELECT * FROM PROVEEDOR_VACUNAS;

CREATE OR REPLACE VIEW VIEW_SERVICIOS AS
SELECT * FROM SERVICIOS;

CREATE OR REPLACE VIEW VIEW_PRODUCTOS AS
SELECT * FROM PRODUCTOS;

CREATE OR REPLACE VIEW VIEW_VACUNAS AS
SELECT * FROM VACUNAS;

CREATE OR REPLACE VIEW VIEW_SERVICIO_MASCOTA AS
SELECT * FROM SERVICIO_MASCOTA;

CREATE OR REPLACE VIEW VIEW_CONSULTAS AS
SELECT * FROM CONSULTAS;

CREATE OR REPLACE VIEW VIEW_VENTAS AS
SELECT * FROM VENTAS;

CREATE OR REPLACE VIEW VIEW_VACUNACIONES AS
SELECT * FROM VACUNACIONES;


CREATE OR REPLACE VIEW VIEW_VENTAS_DETALLES AS
SELECT
    V.ID_VENTA,
    C.NOM_CLIENTE,
    P.NOM_PROD,
    V.DESCRIPCION,
    V.CANTIDAD
FROM
    VENTAS V
JOIN CLIENTES C ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUCTOS P ON V.ID_PRODUCTO = P.ID_PRODUCTO;


CREATE OR REPLACE VIEW VIEW_CONSULTAS_DETALLES AS
SELECT
    C.ID_CONSULTA,
    M.NOM_MASCOTA,
    V.NOM_VET,
    C.FECHA,
    C.TIPO_CONSULTA,
    C.COSTO_CONSULTA
FROM
    CONSULTAS C
JOIN MASCOTAS M ON C.ID_MASCOTA = M.ID_MASCOTA
JOIN VETERINARIOS V ON C.NUM_CEDULA = V.NUM_CEDULA;

CREATE OR REPLACE VIEW VIEW_VENTAS_CLIENTE_PRODUCTO AS
SELECT
    V.ID_VENTA,
    C.NOM_CLIENTE,
    P.NOM_PROD,
    V.DESCRIPCION,
    V.CANTIDAD
FROM
    VENTAS V
JOIN CLIENTES C ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUCTOS P ON V.ID_PRODUCTO = P.ID_PRODUCTO;

CREATE OR REPLACE VIEW VIEW_CLIENTES_MASCOTAS AS
SELECT
    C.ID_CLIENTE,
    C.NOM_CLIENTE,
    C.AP_PATERNO,
    M.NOM_MASCOTA,
    M.RAZA,
    M.GENERO,
    M.ESPECIE,
    M.FEC_NAC,
    M.COLOR,
    M.PESO,
    M.TATUAJE
FROM
    CLIENTES C
JOIN MASCOTAS M ON C.ID_CLIENTE = M.ID_CLIENTE;
